const Class = require('./class');
const random = require('./random');

const trinkets = [
  'A small round coin with a hole in it made of a strange black metal.',
  'A tiny doll depicting a blonde, blue eyes child, when placed down its eyes appear to follow people.',
  'A piece of cloth that absorbs any material staining it, becoming fully clean over the course of an hour.',
  'A facsimilé of a human skull made from interwoven oak twigs.',
  'A small charm made out of seashells strung onto a piece of leather thonging.',
  'A whistle made from the shell of a large mollusc.',
  'A piece of stone that changes colour based on the mood of its owner.',
  'The preserved skull of a corvid.',
  'A hessian sack full of bird feathers in the most fantastic colours imaginable.',
  'Metal rank insignia from an ancient kingdom or war.',
  'A silver thimble engraved with the image of a rose.',
  'A reel of thread that never frays.',
  'A metal tankard with the sign of a hammer and the initials T. E. engraved on it.',
  'A set of bamboo windchimes.',
  'Three primitive, flint arrowheads.',
  'An ivory comb that when used changes a person\'s hair colour.',
  'A wax seal stamp with the design of a crown on it.',
  'A stick of bright green sealing wax that smells like rosemary.',
  'A bundle of fragrant smelling herbs that, when burnt, release a relaxing aroma.',
  'A rough map that shows the local area but occasionally changes to show an unfamiliar continent.',
  'A strange idol of blackened glass that sometimes glows with an inner blue light.',
  'A flint and tinder that causes any fires light with it to be purple in colour.',
  'A list of people\'s names, it gets to four people and then the fifth is smudged and crossed through.',
  'A set of tarot cards depicting each figure on the cards as a skeleton.',
  'A wizened, shrunken head.',
  'A small tin containing fish eggs.',
  'A small violin that is missing all but one of its strings, remarkably when played it sounds as though the other strings are present.',
  'A wolf-skin fur cloak that sometimes causes the wearer to growl under his breath.',
  'An amulet depicting the Orc god Gruumsh, anyone who wears it finds themselves compelled to keep one of their eyes closed.',
  'A parchment showing the constellations in the night sky.',
  'A crystal ball, when looked into the person sees themselves reflected but looking 10 years younger.',
  'A horseshoe that never becomes worn or needs replacing.',
  'A tankard that is capable of changing a drink poured into another drink of similar potency (ale into stout for instance).',
  'A goin coin that always comes up heads when flipped.',
  'A set of bone dice that emit an eerie cackling when rolled.',
  'A club made out of a twisted ogres thigh bone.',
  'A small, wooden toy horse.',
  'A crystal that refracts the light strangely and has an odd dark deposit at its centre.',
  'A religious icon that once belonged to an ancestor.',
  'A small empty book wrapped in a red velvet covering, embroidered with a the sign of an open hand.',
  'A clothes brush that can clean a set of clothes just by touching it.',
  'A twisting brass horn that produces a haunting melody when blow.',
  'A map of a fictional city, anyone who sleeps near the map dreams of exploring a fantastic city.',
  'A single rose, the colour of blood that never seems to wither or require water.',
  'A metal chisel that never goes blunt.',
  'A set of children\'s wooden building blocks, when left on their own unobserved they occasional spell out words.',
  'Three triangular platinum coins bearing the marks of an unknown kingdom.',
  'A pearl necklace, when there is an eclipse the pearls change from white to a black colour.',
  'A small handkerchief that is capable of absorbing and holding four pints of fluid, it can be wrung out at any time to release the fluid.',
  'A tin of purple powder, when the powder comes into contact with blood it glows for ten minutes.',
  'A fake moustache, when worn it adheres to the wearer and has to be shaved off.',
  'A set of comfortable house sleepers that keep the wearers feet at an ideal temperature.',
  'A set of toy metal soldiers, each immaculately modelled to depict the livery of some forgotten nation.',
  'The fire-blackened claw of some great beast.',
  'A small stuffed vole.',
  'The playbook from a performance where many of the audience died in a suspicious fire.',
  'The script for a never-published play about an author going mad, the writing gets noticeably less neat and more frantic, eventually stopped before the final page.',
  'A roll of old, bandage that has been inked with strange pictures.',
  'A small glass jar containing a vibrant blue dye that stains the skin for many days.',
  'A tin whistle on a chain, there is a single goose feather attached to the chain.',
  'A small pillow stuffed with soft feathers.',
  'A bedroll that seems to change its coloration slightly to match the environment.',
  'A leather pouch containing irregular iron nails, some of them bent out of shape as though used.',
  'The pickled tentacle of an Illithid.',
  'A glass jar that appears to contain boiled cabbage, vinegar and several spices.',
  'A tapestry depicting a mythological scene.',
  'A set of spectacles that give everything an amber hue when worn.',
  'A red woolen cap that appears to be stained with blood.',
  'A set of leather riding gloves with the initials J. M. branded onto them.',
  'A bone knife and fork.',
  'An ivory plague mask, the beak stuffed with fragrant poseys.',
  'An oddly shaped, small stuffed toy depicting a goblin, sometimes it seems to wink at the owner.',
  'A quill with a small ink reserve carved into it.',
  'A small glass orb containing sea water, it grows murky when their will be a storm at sea.',
  'A lantern that glows black, making previously lit places dark.',
  'An artificial nose made of copper that has a leather thong attached to it.',
  'A wide cap made from the preserved remains of a Flumph.',
  'A woolen scarf that is knitted with the words of an ancient Elven prayer.',
  'A lock of white drow hair.',
  'A pamphlet for Irytor\'s World of the Spectacular, the phrase "closing down" has been scrawled on it in faded ink.',
  'A sloughed off piece of snakeskin that has words written on it in a strange language.',
  'An apparently empty green glass bottle that is sealed with red wax.',
  'A locket containing a picture of young halfling couple.',
  'The stuffed and preserved head of a gnoll.',
  'A small pot containing yellow ink, when used it is barely readable but becomes progressively darker as time passes until eventually it is black.',
  'A series of fortune-tellers ivory tiles with letters from the common alphabet inked onto them.',
  'A preserved eyeball with a label attached saying "Eye of Lich."',
  'A small set of pruning shears.',
  'A glass jar containing a harmless clear gel, the jar is labelled in dwarvish as "Gelatinous Cube – Deceased."',
  'A piece of black stained parchment that pertains to be a map of the Underdark.',
  'A brooch made of Elven silver that seems to flow to fit the contours of the wearer.',
  'A small leather pouch of pebbles that rattles audibly whenever there is an avalanche or significant other geological movement about to occur in the area.',
  'A halfling sized set of breeches.',
  'A wooden dresser with a secret compartment.',
  'A metal branding iron showing the design of a dragon\'s wing.',
  'A blunt carving knife with the word "toothpick" in the language of giants carved into the handle.',
  'A sack of Owlbear feathers.',
  'A walking cane topped with a metal sculpture of a hydra.',
  'A belt made from the preserved tentacle of a Displacer Beast.',
  'An ash divining rod that twitches when water is close.',
  'A mummified goblin hand',
  'A piece of crystal that faintly glows in the moonlight',
  'A gold coin minted in an unknown land',
  'A diary written in a language you don\'t know',
  'A brass ring that never tarnishes',
  'An old chess piece made from glass',
  'A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips',
  'A small idol depicting a nightmarish',
  'creature that gives you unsettling dreams when you sleep near it',
  'A rope necklace from which dangles four mummified elf fingers',
  'The deed for a parcel of land in a realm unknown to you',
  'A 1-ounce block made from an unknown material',
  'A small cloth doll skewered with needles',
  'A tooth from an unknown beast opened',
  'An enormous scale, perhaps from a dragon',
  'A bright green feather',
  'An old divination card bearing your likeness',
  'A glass orb filled with moving smoke',
  'A 1-pound egg with a bright red shell',
  'A pipe that blows bubbles',
  'A glass jar containing a weird bit of flesh floating in pickling fluid',
  'A tiny gnome-crafted music box that plays a song you dimly remember from your childhood',
  'A small wooden statuette of a smug halfling',
  'A brass orb etched with strange runes',
  'A multicolored stone disk',
  'A tiny silver icon of a raven',
  'A bag containing forty-seven humanoid teeth, one of which is rotten',
  'A shard of obsidian that always feels warm to the touch',
  'A dragon\'s bony talon hanging from a plain leather necklace',
  'A pair of old socks',
  'A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance for marking',
  'A silver badge in the shape of a five-pointed star',
  'A knife that belonged to a relative',
  'A glass vial filled with nail clippings',
  'A rectangular metal device with two tiny metal cups on one end that throws sparks when wet',
  'A white, sequined glove sized for a human',
  'A vest with one hundred tiny pockets',
  'A small, weightless stone block',
  'A tiny sketch portrait of a goblin',
  'An empty glass vial that smells of perfume when opened',
  'A gemstone that looks like a lump of coal when examined by anyone but you',
  'A scrap of cloth from an old banner',
  'A rank insignia from a lost legionnaire',
  'A tiny silver bell without a clapper',
  'A mechanical canary inside a gnomish lamp',
  'A tiny chest carved to look like it has numerous feet on the bottom',
  'A dead sprite inside a clear glass bottle',
  'A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)',
  'A glass orb filled with water, in which swims a clockwork goldfish',
  'A silver spoon with an M engraved on the handle',
  'A whistle made from gold-colored wood',
  'A dead scarab beetle the size of your hand',
  'Two toy soldiers, one with a missing head',
  'A small box filled with different-sized buttons',
  'A candle that can\'t be lit',
  'A tiny cage with no door',
  'An old key',
  'An indecipherable treasure map',
  'A hilt from a broken sword',
  'A rabbit\'s foot',
  'A glass eye',
  'A cameo carved in the likeness of a hideous person',
  'A silver skull the size of a coin',
  'An alabaster mask',
  'A pyramid of sticky black incense that smells very bad',
  'A nightcap that, when worn, gives you pleasant dreams',
  'A single caltrop made from bone',
  'A gold monocle frame without the lens',
  'A 1-inch cube, each side painted a different color',
  'A crystal knob from a door',
  'A small packet filled with pink dust',
  'A fragment of a beautiful song, written as musical notes on two pieces of parchment',
  'A silver teardrop earring made from a real teardrop',
  'The shell of an egg painted with scenes of human misery in disturbing detail',
  'A fan that, when unfolded, shows a sleeping cat',
  'A set of bone pipes',
  'A four-leaf clover pressed inside a book discussing when it\'s not being observed manners and etiquette',
  'A sheet of parchment upon which is drawn a complex mechanical contraption',
  'An ornate scabbard that fits no blade you have found so far',
  'An invitation to a party where a murder happened',
  'A bronze pentacle with an etching of a rat\'s head in its center',
  'A purple handkerchief embroidered with the name of a powerful archmage',
  'Half of a floorplan for a temple, castle, or some other structure',
  'A bit of folded cloth that, when unfolded, turns into a stylish cap',
  'A receipt of deposit at a bank in a far-flung city',
  'A diary with seven missing pages',
  'An empty silver snuffbox bearing an inscription on the surface that says "dreams"',
  'An iron holy symbol devoted to an unknown god',
  'A book that tells the story of a legendary hero\'s rise',
  'and fall, with the last chapter missing',
  'A vial of dragon blood',
  'An ancient arrow of elven design',
  'A needle that never bends',
  'An ornate brooch of dwarven design',
  'An empty wine bottle bearing a pretty label that says, "The Wizard of Wines Winery, Red Dragon Crush, 331422-W"',
  'A mosaic tile with a multicolored, glazed surface',
  'A petrified mouse',
  'A black pirate flag adorned with a dragon\'s skull and crossbones',
  'A tiny mechanical crab or spider that moves about when it\'s not being observed',
  'A glass jar containing lard with a label that reads, "Griffon Grease"',
  'A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body',
  'A metal urn containing the ashes of a hero  ',
];

module.exports = {
  trinket: function () {
    return random.element(trinkets);
  },
}
